modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/owoPeef/AdvancedSurvival/issues/"
[[mods]]
modId="advancedsurvival"
version="0.5"
displayName="Advanced Survival"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://api.github.com/repos/owoPeef/AdvancedSurvival/releases"
displayURL="https://github.com/owoPeef/AdvancedSurvival/releases"
logoFile="advancedsurvival.png"
credits="Only one person - im"
authors="owoPeef"
description='''
    This mod will make your world go crazy!
    Advanced Survival is here!
'''
[[dependencies.advancedsurvival]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.advancedsurvival]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
